extends:
  - airbnb
parser: babel-eslint
env:
  jest: true
  browser: true
rules:
  react/jsx-filename-extension: 0
  react/prefer-stateless-function: 0
  react/prop-types: 0
  jsx-a11y/no-static-element-interactions: 0
  class-methods-use-this: 0
  no-underscore-dangle: 0

