# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      # - run:
      #     name: Upload docker image to Hub
      #     command: |
      #       TAG=0.1.$CIRCLE_BUILD_NUM
      #       docker build -t jesse1983/spotifood:$TAG
      #       docker login -u $DOCKER_USER -p $DOCKER_PASS
      #       docker push jesse1983/spotifood:$TAG
      - run: npm run build
      - run:
          name: Export docs to gh-pages branch
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            npm run export
            mv out docs
            git add docs --all
            git commit -m "Docs ${TAG}"
            git push origin gh-pages
