const PLAYLISTS_LIST_BEGIN: 'PLAYLISTS_LIST_BEGIN' = 'PLAYLISTS_LIST_BEGIN';
const PLAYLISTS_LIST_SUCCESS: 'PLAYLISTS_LIST_SUCCESS' =
  'PLAYLISTS_LIST_SUCCESS';
const PLAYLISTS_LIST_APPEND: 'PLAYLISTS_LIST_APPEND' = 'PLAYLISTS_LIST_APPEND';
const PLAYLISTS_LIST_FAILURE: 'PLAYLISTS_LIST_FAILURE' =
  'PLAYLISTS_LIST_FAILURE';

export {
  PLAYLISTS_LIST_APPEND,
  PLAYLISTS_LIST_BEGIN,
  PLAYLISTS_LIST_SUCCESS,
  PLAYLISTS_LIST_FAILURE,
};
